---
name: PyPI
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: {}

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Download
        shell: bash
        run: |
          set -euo pipefail
          IFS=$'\n\t'
          pip install randalf
